# generated by datamodel-codegen:
#   timestamp: 2026-09-14T07:08:59+00:00

from typing import Any, Literal, NotRequired

from typing_extensions import TypedDict


class SimpleUser(TypedDict):
    """
    A GitHub user.
    """

    name: NotRequired[str]
    email: NotRequired[str]
    login: str
    id: int
    node_id: str
    avatar_url: str
    gravatar_id: str
    url: str
    html_url: str
    followers_url: str
    following_url: str
    gists_url: str
    starred_url: str
    subscriptions_url: str
    organizations_url: str
    repos_url: str
    events_url: str
    received_events_url: str
    type: str
    site_admin: bool
    starred_at: NotRequired[str]
    user_view_type: NotRequired[str]


class NullableSimpleUser(TypedDict):
    """
    A GitHub user.
    """

    name: NotRequired[str]
    email: NotRequired[str]
    login: str
    id: int
    node_id: str
    avatar_url: str
    gravatar_id: str
    url: str
    html_url: str
    followers_url: str
    following_url: str
    gists_url: str
    starred_url: str
    subscriptions_url: str
    organizations_url: str
    repos_url: str
    events_url: str
    received_events_url: str
    type: str
    site_admin: bool
    starred_at: NotRequired[str]
    user_view_type: NotRequired[str]


class Label(TypedDict):
    """
    Color-coded labels help you categorize and filter your issues (just like labels in Gmail).
    """

    id: int
    node_id: str
    url: str
    name: str
    description: str
    color: str
    default: bool
    archived_at: str
    archived_by: SimpleUser


class Permissions(TypedDict, extra_items=str):
    """
    The set of permissions for the GitHub app
    """

    issues: NotRequired[str]
    checks: NotRequired[str]
    metadata: NotRequired[str]
    contents: NotRequired[str]
    deployments: NotRequired[str]


ReactionRollup = TypedDict(
    "ReactionRollup",
    {
        "url": str,
        "total_count": int,
        "+1": int,
        "-1": int,
        "laugh": int,
        "confused": int,
        "heart": int,
        "hooray": int,
        "eyes": int,
        "rocket": int,
    },
)


class Head(TypedDict):
    ref: str
    label: str
    sha: str


class Base(TypedDict):
    ref: str
    label: str
    sha: str


class Reaction(TypedDict):
    """
    Reactions to conversations provide a way to help people express their feelings more simply and effectively.
    """

    id: int
    node_id: str
    user: NullableSimpleUser
    content: Literal["+1", "-1", "laugh", "confused", "heart", "hooray", "rocket", "eyes"]
    created_at: str


class PullRequest(TypedDict):
    """
    Pull requests let you tell others about changes you've pushed to a repository on GitHub. Once a pull request is sent, interested parties can review the set of changes, discuss potential modifications, and even push follow-up commits if necessary.
    """

    url: str
    id: int
    node_id: str
    html_url: str
    diff_url: str
    patch_url: str
    issue_url: str
    commits_url: str
    review_comments_url: str
    review_comment_url: str
    comments_url: str
    statuses_url: str
    number: int
    state: Literal["open", "closed"]
    locked: bool
    title: str
    user: SimpleUser
    body: str
    labels: list[Label]
    milestone: dict[str, Any] | None
    active_lock_reason: NotRequired[str]
    created_at: str
    updated_at: str
    closed_at: str
    merged_at: str
    merge_commit_sha: str
    assignee: NullableSimpleUser
    assignees: NotRequired[list[dict[str, Any]]]
    requested_reviewers: NotRequired[list[dict[str, Any]]]
    requested_teams: NotRequired[list[dict[str, Any]]]
    head: Head
    base: Base
    field_links: dict[str, Any]
    author_association: str
    auto_merge: dict[str, Any] | None
    stack: NotRequired[dict[str, Any] | None]
    draft: NotRequired[bool]
    merged: bool
    mergeable: bool
    rebaseable: NotRequired[bool]
    mergeable_state: str
    merged_by: NullableSimpleUser
    comments: int
    review_comments: int
    maintainer_can_modify: bool
    commits: int
    additions: int
    deletions: int
    changed_files: int


class PullRequestReview(TypedDict):
    """
    Pull Request Reviews are reviews on pull requests.
    """

    id: int
    node_id: str
    user: NullableSimpleUser
    body: str
    state: str
    html_url: str
    pull_request_url: str
    field_links: dict[str, Any]
    submitted_at: NotRequired[str]
    commit_id: str
    body_html: NotRequired[str]
    body_text: NotRequired[str]
    author_association: str


class NullableIntegration(TypedDict):
    """
    GitHub apps are a new way to extend GitHub. They can be installed directly on organizations and user accounts and granted access to specific repositories. They come with granular permissions and built-in webhooks. GitHub apps are first class actors within GitHub.
    """

    id: int
    slug: NotRequired[str]
    node_id: str
    client_id: NotRequired[str]
    owner: SimpleUser | Any
    name: str
    description: str
    external_url: str
    html_url: str
    created_at: str
    updated_at: str
    permissions: Permissions
    events: list[str]
    installations_count: NotRequired[int]


class IssueComment(TypedDict):
    """
    Comments provide a way for people to collaborate on an issue.
    """

    id: int
    node_id: str
    url: str
    body: NotRequired[str]
    body_text: NotRequired[str]
    body_html: NotRequired[str]
    html_url: str
    user: NullableSimpleUser
    created_at: str
    updated_at: str
    issue_url: str
    author_association: NotRequired[Any]
    performed_via_github_app: NotRequired[NullableIntegration]
    reactions: NotRequired[ReactionRollup]
    pin: NotRequired[Any]
    minimized: NotRequired[Any]


class PullRequestSimple(TypedDict):
    """
    Pull Request Simple
    """

    url: str
    id: int
    node_id: str
    html_url: str
    diff_url: str
    patch_url: str
    issue_url: str
    commits_url: str
    review_comments_url: str
    review_comment_url: str
    comments_url: str
    statuses_url: str
    number: int
    state: str
    locked: bool
    title: str
    user: dict[str, Any] | None
    body: str
    labels: list[Label]
    milestone: dict[str, Any] | None
    active_lock_reason: NotRequired[str]
    created_at: str
    updated_at: str
    closed_at: str
    merged_at: str
    merge_commit_sha: str
    assignee: dict[str, Any] | None
    assignees: NotRequired[list[dict[str, Any]]]
    requested_reviewers: NotRequired[list[dict[str, Any]]]
    requested_teams: NotRequired[list[dict[str, Any]]]
    head: Head
    base: Base
    field_links: dict[str, Any]
    author_association: str
    auto_merge: dict[str, Any] | None
    stack: NotRequired[Any]
    draft: NotRequired[bool]


class Deployment(TypedDict):
    """
    A request for a specific ref(branch,sha,tag) to be deployed
    """

    url: str
    id: int
    node_id: str
    sha: str
    ref: str
    task: str
    payload: dict[str, Any] | str
    original_environment: NotRequired[str]
    environment: str
    description: str
    creator: NullableSimpleUser
    created_at: str
    updated_at: str
    statuses_url: str
    repository_url: str
    transient_environment: NotRequired[bool]
    production_environment: NotRequired[bool]
    performed_via_github_app: NotRequired[NullableIntegration]


class DeploymentStatus(TypedDict):
    """
    The status of a deployment.
    """

    url: str
    id: int
    node_id: str
    state: Literal["error", "failure", "inactive", "pending", "success", "queued", "in_progress"]
    creator: NullableSimpleUser
    description: str
    environment: NotRequired[str]
    target_url: str
    created_at: str
    updated_at: str
    deployment_url: str
    repository_url: str
    environment_url: NotRequired[str]
    log_url: NotRequired[str]
    performed_via_github_app: NotRequired[NullableIntegration]
